name: extended_image_library
description: package library for extended_image, extended_text and extended_text_field, provide common base class.
version: 3.6.0
publish_to: none
homepage: https://github.com/fluttercandies/extended_image_library

environment:
  sdk: '>=3.5.2 <4.0.0'
  flutter: '>=3.13.0'

dependencies:
  crypto: ^3.0.5
  flutter:
    sdk: flutter

  http_client_helper: ^3.0.0
  js: ^0.7.1
  path: ^1.9.0  
  path_provider:
    git: https://github.com/kumsumit/path_provider.git





