name: extended_image_library
description: Library that contains common base class for `extended_image`, `extended_text`, and `extended_text_field`.
repository: https://github.com/fluttercandies/extended_image_library
publish_to: none
version: 5.0.0

environment:
  sdk: ^3.7.0
  flutter: ">=3.29.0"

dependencies:
  crypto: ^3.0.6
  flutter:
    sdk: flutter
  http_client_helper: ^3.0.0
  path: ^1.9.1
  path_provider:
    git: https://github.com/kumsumit/path_provider.git
  web: ">=1.1.1 <10.0.0"
